#!/usr/bin/env bash
#
# post-setup.sh - TaskSquad Post-Setup Rebuild
#
# Run this after adding content to rebuild indexes and verify setup.
# Executes wiki lint, graphify rebuild, and checks canonical-facts.md.
#
# Usage: ./core/scripts/post-setup.sh [--wiki-only] [--graphify-only] [--check-only]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Parse arguments
RUN_WIKI=true
RUN_GRAPHIFY=true
CHECK_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --wiki-only)
      RUN_GRAPHIFY=false
      ;;
    --graphify-only)
      RUN_WIKI=false
      ;;
    --check-only)
      CHECK_ONLY=true
      ;;
    --help|-h)
      echo "Usage: $0 [--wiki-only] [--graphify-only] [--check-only]"
      echo ""
      echo "Options:"
      echo "  --wiki-only      Only run wiki lint"
      echo "  --graphify-only  Only rebuild graphify"
      echo "  --check-only     Only check status, don't rebuild"
      exit 0
      ;;
  esac
done

# Color output (degrades gracefully)
if [[ -t 1 ]] && command -v tput &>/dev/null; then
  RED=$(tput setaf 1 2>/dev/null || echo "")
  GREEN=$(tput setaf 2 2>/dev/null || echo "")
  YELLOW=$(tput setaf 3 2>/dev/null || echo "")
  BLUE=$(tput setaf 4 2>/dev/null || echo "")
  RESET=$(tput sgr0 2>/dev/null || echo "")
else
  RED="" GREEN="" YELLOW="" BLUE="" RESET=""
fi

info()    { echo "${BLUE}[INFO]${RESET} $*"; }
success() { echo "${GREEN}[OK]${RESET} $*"; }
warn()    { echo "${YELLOW}[WARN]${RESET} $*"; }
error()   { echo "${RED}[ERROR]${RESET} $*"; }

graphify_inputs() {
  local rel
  for rel in data/wiki data/guides data/standards core/docs/standards core/templates docs; do
    if [[ -d "$REPO_ROOT/$rel" ]]; then
      printf '%s\n' "$rel"
    fi
  done
}

graphify_slash_command() {
  local inputs
  inputs="$(graphify_inputs | tr '\n' ' ' | sed 's/[[:space:]]*$//')"
  echo "/graphify $inputs --update"
}

try_generate_graphify() {
  local -a inputs=()
  local rel

  while IFS= read -r rel; do
    [[ -n "$rel" ]] && inputs+=("$rel")
  done < <(graphify_inputs)

  if [[ ${#inputs[@]} -eq 0 ]]; then
    warn "No graphify input directories found"
    return 1
  fi

  if command -v graphify &>/dev/null; then
    if (cd "$REPO_ROOT" && graphify "${inputs[@]}" --update); then
      success "Graphify knowledge graph generated"
      return 0
    fi
    warn "graphify command failed"
  fi

  if python3 -m graphify --help &>/dev/null; then
    if (cd "$REPO_ROOT" && python3 -m graphify "${inputs[@]}" --update); then
      success "Graphify knowledge graph generated via python module"
      return 0
    fi
    warn "python graphify runner failed"
  fi

  warn "No shell graphify runner succeeded"
  warn "Open Claude Code in this repo and run: $(graphify_slash_command)"
  return 1
}

ERRORS=0

echo "========================================"
echo "      TaskSquad Post-Setup Rebuild"
echo "========================================"
echo ""

# ============================================================================
# Wiki Lint
# ============================================================================

if [[ "$RUN_WIKI" == "true" ]]; then
  info "Running wiki lint..."

  WIKI_DIR="$REPO_ROOT/data/wiki"
  LINT_SCRIPT="$REPO_ROOT/core/scripts/lint-wiki.sh"

  if [[ ! -d "$WIKI_DIR" ]]; then
    warn "Wiki directory not found: $WIKI_DIR"
    warn "Create data/wiki/ and add pages before running lint"
    ERRORS=$((ERRORS + 1))
  elif [[ ! -f "$LINT_SCRIPT" ]]; then
    error "Wiki lint script not found: $LINT_SCRIPT"
    ERRORS=$((ERRORS + 1))
  else
    if [[ "$CHECK_ONLY" == "true" ]]; then
      info "Wiki lint: would run $LINT_SCRIPT"
    else
      if "$LINT_SCRIPT" "$WIKI_DIR"; then
        success "Wiki lint: passed"
      else
        warn "Wiki lint: found issues (see report above)"
        ERRORS=$((ERRORS + 1))
      fi
    fi
  fi

  echo ""
fi

# ============================================================================
# Graphify Rebuild
# ============================================================================

if [[ "$RUN_GRAPHIFY" == "true" ]]; then
  info "Checking graphify status..."

  # Check if graphify is available
  if python3 -c "import graphify" 2>/dev/null; then
    success "Graphify Python package: available"

    GRAPHIFY_OUT="$REPO_ROOT/graphify-out"
    if [[ -d "$GRAPHIFY_OUT" ]] && [[ -f "$GRAPHIFY_OUT/graph.json" ]]; then
      GRAPH_AGE=$(find "$GRAPHIFY_OUT/graph.json" -mmin +60 2>/dev/null | wc -l)
      if [[ "$GRAPH_AGE" -gt 0 ]]; then
        warn "Graphify graph.json is older than 1 hour"
        info "Consider rebuilding with: $(graphify_slash_command)"
      else
        success "Graphify graph.json: recent"
      fi
    else
      info "No existing graphify output found"
      info "Build with: $(graphify_slash_command)"
    fi

    if [[ "$CHECK_ONLY" == "false" ]]; then
      if ! try_generate_graphify; then
        warn "Graphify was not generated by shell. Use the Claude Code fallback above."
      fi
    fi
  else
    warn "Graphify Python package not installed"
    warn "Install with: python3 -m pip install graphifyy"
    ERRORS=$((ERRORS + 1))
  fi

  echo ""
fi

# ============================================================================
# Canonical Facts Check
# ============================================================================

info "Checking canonical-facts.md..."

CANONICAL_FACTS="$REPO_ROOT/data/project/data/canonical-facts.md"

if [[ -f "$CANONICAL_FACTS" ]]; then
  LINES=$(wc -l < "$CANONICAL_FACTS" 2>/dev/null || echo "0")
  if [[ "$LINES" -lt 5 ]]; then
    warn "canonical-facts.md exists but seems sparse ($LINES lines)"
    warn "Add project-specific facts to: $CANONICAL_FACTS"
  else
    success "canonical-facts.md: present ($LINES lines)"
  fi
else
  warn "canonical-facts.md not found"
  warn "Create at: $CANONICAL_FACTS"
  info "This file provides project context injected by the canonical-infra-inject hook"
fi

echo ""

# ============================================================================
# Hooks Check
# ============================================================================

info "Checking hooks configuration..."

HOOKS_DIR="$HOME/.claude/hooks"

if [[ -d "$HOOKS_DIR" ]]; then
  HOOK_COUNT=$(find "$HOOKS_DIR" -name "*.sh" -type f 2>/dev/null | wc -l)
  success "Hooks directory: $HOOK_COUNT shell scripts"

  # Check for key hooks
  if [[ -f "$HOOKS_DIR/canonical-facts-inject.sh" ]]; then
    success "canonical-facts-inject.sh: present"
  else
    warn "canonical-facts-inject.sh: not found"
  fi

  if [[ -f "$HOOKS_DIR/rtk-rewrite.sh" ]]; then
    success "rtk-rewrite.sh: present"
  else
    info "rtk-rewrite.sh: not found (RTK hook is optional)"
  fi
else
  info "Hooks directory not found: $HOOKS_DIR"
  info "Hooks are optional but recommended"
fi

echo ""

# ============================================================================
# Summary
# ============================================================================

echo "========================================"
echo "              SUMMARY"
echo "========================================"
echo ""

if [[ "$ERRORS" -eq 0 ]]; then
  success "All checks passed!"
else
  warn "$ERRORS issue(s) found - see above for details"
fi

echo ""
echo "Reminder: If graphify-out/GRAPH_REPORT.md is missing, run in Claude Code:"
echo "  $(graphify_slash_command)"
echo ""

if [[ "$ERRORS" -gt 0 ]]; then
  exit 1
fi

exit 0
